apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: grafana
    namespace: grafana
spec:
    releaseName: grafana
    chart:
        spec:
            chart: grafana
            sourceRef:
                kind: HelmRepository
                name: grafana-repo
                namespace: grafana
    interval: 50m
    install:
        remediation:
            retries: 3
    values:
        grafana.ini:
            server:
                root_url: https://srv.guibi.dev

        persistence:
            enabled: true
            type: pvc

        ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - srv.guibi.dev
            tls:
              - hosts:
                  - srv.guibi.dev
                secretName: tls-guibi.dev
