apiVersion: v1
kind: PersistentVolume
metadata:
    name: sonarr-media-pv
spec:
    capacity:
        storage: 2000Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
        path: /mnt/Data/Media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sonarr-media-pvc
    namespace: apps
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
          storage: 2000Gi
    volumeName: sonarr-media-pv
    storageClassName: ""

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: sonarr-config-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
        path: /mnt/SSD/app-storage/sonarr

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sonarr-config-pvc
    namespace: apps
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    volumeName: sonarr-config-pv
    storageClassName: ""
