apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: sonarr
    namespace: apps
spec:
    releaseName: sonarr
    chart:
        spec:
            chart: sonarr
            sourceRef:
                kind: HelmRepository
                name: servarr-repo
                namespace: apps
    interval: 50m
    install:
        remediation:
            retries: 3

    values:
        application:
            urlBase: /
        deployment:
            volumes:
                config:
                    persistentVolumeClaim:
                        claimName: sonarr-config-pvc
                tv:
                    persistentVolumeClaim:
                        claimName: sonarr-media-pvc
                downloads:
                    persistentVolumeClaim:
                        claimName: transmission-download-pvc

        persistentVolumeClaims: []

        metrics:
            enabled: false

        ingress:
            enabled: true
            annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
            host: sonarr.guibi.dev
            path: /
            pathType: ImplementationSpecific
            tls:
              - secretName: tls-guibi.dev
                hosts:
                  - sonarr.guibi.dev
