apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: vaultwarden-cluster
    namespace: cnpg
spec:
    description: "Vaultwarden cluster"
    imageName: ghcr.io/cloudnative-pg/postgresql:17.4
    instances: 3
    startDelay: 300
    stopDelay: 300
    primaryUpdateStrategy: unsupervised
    enableSuperuserAccess: true

    postgresql:
        parameters:
            shared_buffers: 256MB
            pg_stat_statements.max: "10000"
            pg_stat_statements.track: all
            auto_explain.log_min_duration: "10s"

    bootstrap:
        initdb:
            database: vaultwarden
            owner: vaultwarden
            secret:
                name: vaultwarden-cluster-secret

    storage:
        storageClass: openebs-zfspv
        size: 10Gi

    walStorage:
        storageClass: openebs-zfspv
        size: 50Gi

    backup:
        retentionPolicy: "14d"
        barmanObjectStore:
            destinationPath: s3://vaultwarden/
            endpointURL: https://minio.cnpg.svc.cluster.local
            endpointCA:
                name: cnpg-minio-tenant-ca-tls
                key: ca.crt
            s3Credentials:
                accessKeyId:
                    name: cnpg-wal-minio-credentials
                    key: CONSOLE_ACCESS_KEY
                secretAccessKey:
                    name: cnpg-wal-minio-credentials
                    key: CONSOLE_SECRET_KEY
            wal:
                compression: snappy

        # Volume snapshot backups
        volumeSnapshot:
            className: openebs-zfspv-snapshot

    monitoring:
        enablePodMonitor: true

    resources:
        requests:
            memory: "512Mi"
            cpu: 50m
        limits:
            memory: "1Gi"
            cpu: 1000m

    affinity:
        enablePodAntiAffinity: true
        topologyKey: failure-domain.beta.kubernetes.io/zone

    nodeMaintenanceWindow:
        inProgress: false
        reusePVC: false

---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: vaultwarden-cluster-secret
    namespace: cnpg
data:
    username: dmF1bHR3YXJkZW4=
    password: dmF1bHR3YXJkZW4=

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
    name: vaultwarden-cluster-backup
    namespace: cnpg
spec:
    cluster:
        name: vaultwarden-cluster
    method: volumeSnapshot
    schedule: "0 0 0 * * *"
    backupOwnerReference: cluster
    immediate: true
