apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden
    namespace: apps
spec:
    releaseName: vaultwarden
    chart:
        spec:
            chart: vaultwarden
            sourceRef:
                kind: HelmRepository
                name: vaultwarden-repo
                namespace: apps
    interval: 50m
    install:
        remediation:
            retries: 3
    values:
        domain: https://vault.guibi.dev/

        database:
            type: postgresql
            uriOverride: postgresql://vaultwarden:vaultwarden@vaultwarden-cluster-rw.apps.svc.cluster.local:5432/vaultwarden

        ingress:
            enabled: true
            class: traefik
            additionalAnnotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
            hostname: vault.guibi.dev
            tlsSecret: tls-guibi.dev
