apiVersion: seaweed.seaweedfs.com/v1
kind: Bucket
metadata:
    name: cnpg-vaultwarden
    namespace: vaultwarden
spec:
    clusterRef:
        name: cnpg-seaweed
        namespace: cnpg

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
    name: cnpg-backups
    namespace: vaultwarden
spec:
    name: cnpg-backups-vaultwarden
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
    name: cnpg-backups-credentials
    namespace: vaultwarden
spec:
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg
    identityRef:
        name: cnpg-backups-vaultwarden
    secretRef:
        name: cnpg-backups-s3-credentials

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Policy
metadata:
    name: cnpg-backups-policy
    namespace: vaultwarden
spec:
    name: cnpg-backups-policy-vaultwarden
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg
    statements:
        - effect: Allow
          actions:
              - s3:*
          resources:
              - cnpg-vaultwarden
              - cnpg-vaultwarden/*

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3PolicyBinding
metadata:
    name: cnpg-backups-policy-binding
    namespace: vaultwarden
spec:
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg
    policyRef:
        name: cnpg-backups-policy-vaultwarden
    subjects:
        - kind: S3Identity
          name: cnpg-backups-vaultwarden
