apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: cnpg-wal-minio
    namespace: monitoring
    labels:
        release: prometheus
spec:
    selector:
        matchLabels:
            name: minio
    namespaceSelector:
        matchNames:
          - cnpg
    endpoints:
      - port: https-minio
        path: /minio/v2/metrics/cluster
        scheme: https
        interval: 30s
        tlsConfig:
            insecureSkipVerify: true
