apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: cnpg-wal-minio
    namespace: cnpg
spec:
  selector:
      matchLabels:
          v1.min.io/tenant: cnpg-wal-minio
  namespaceSelector: {}
  podMetricsEndpoints:
      - port: https-minio
        path: /minio/v2/metrics/cluster
        scheme: https
        interval: 30s
        tlsConfig:
            insecureSkipVerify: true
