apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: promtail
    namespace: monitoring
spec:
    interval: 5m
    timeout: 1m
    dependsOn:
      - name: prometheus
    chart:
        spec:
            chart: promtail
            sourceRef:
                kind: HelmRepository
                name: grafana-repo
                namespace: monitoring
            interval: 60m

    values:
        config:
            clients:
              - url: http://loki-gateway/loki/api/v1/push
                tenant_id: 1
