apiVersion: v1
kind: PersistentVolume
metadata:
    name: opencloud-config-pv
    namespace: opencloud
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /mnt/SSD/app-storage/opencloud

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: opencloud-config-pvc
    namespace: opencloud
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    volumeName: opencloud-config-pv
    storageClassName: ""

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: opencloud-data-pv
    namespace: opencloud
spec:
    capacity:
        storage: 1000Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /mnt/Data/OpenCloud

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: opencloud-data-pvc
    namespace: opencloud
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1000Gi
    volumeName: opencloud-data-pv
    storageClassName: ""
