apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: opencloud-repo
    namespace: opencloud
spec:
    type: oci
    url: oci://ghcr.io/tim-herbie/opencloud-helm
    interval: 5m
