apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: cert-manager-repo
    namespace: cert-manager
spec:
    type: default
    url: https://charts.jetstack.io
    interval: 24h
