apiVersion: v1
kind: PersistentVolume
metadata:
    name: radarr-media-pv
    namespace: apps
spec:
    capacity:
        storage: 3000Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
        path: /mnt/Data/Media/Films

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: radarr-media-pvc
    namespace: apps
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 3000Gi
    volumeName: radarr-media-pv
    storageClassName: ""

---

apiVersion: v1
kind: PersistentVolume
metadata:
    name: radarr-config-pv
    namespace: apps
spec:
    capacity:
        storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
        path: /mnt/SSD/app-storage/radarr

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: radarr-config-pvc
    namespace: apps
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 100Gi
    volumeName: radarr-config-pv
    storageClassName: open
