apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: radarr
    namespace: apps
spec:
    releaseName: radarr
    chart:
        spec:
            chart: radarr
            sourceRef:
                kind: HelmRepository
                name: servarr-repo
                namespace: apps
    interval: 50m
    install:
        remediation:
            retries: 3

    values:
        application:
            urlBase: /radarr

        deployment:
            volumes:
                config:
                    persistentVolumeClaim:
                        claimName: radarr-config-pvc
                film:
                    persistentVolumeClaim:
                        claimName: radarr-media-pvc
                downloads:
                    persistentVolumeClaim:
                        claimName: transmission-download-pvc

        secrets:
            - name: apiKey
              value: d11c7839ad5a183da80e9de80665561f

        persistentVolumeClaims: []

        metrics:
            enabled: true

        ingress:
            enabled: true
            annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
                traefik.ingress.kubernetes.io/router.middlewares: apps-pocket-id-auth-radarr@kubernetescrd
            host: seer.guibi.dev
            path: /radarr
            pathType: Prefix
            tls:
                - secretName: tls-guibi.dev
                  hosts:
                      - seer.guibi.dev
