apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: radarr
    namespace: apps
spec:
    releaseName: radarr
    chart:
        spec:
            chart: radarr
            sourceRef:
                kind: HelmRepository
                name: servarr-repo
                namespace: apps
    interval: 50m
    install:
        remediation:
            retries: 3
    values:
        deployment:
            volumes:
                config:
                    persistentVolumeClaim:
                        claimName: radarr-config-pvc
                downloads:
                    persistentVolumeClaim:
                        claimName: radarr-media-pvc
                film:
                    persistentVolumeClaim:
                        claimName: transmission-download-pvc

        metrics:
            enabled: false

        ingress:
            enabled: true
            annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - host: radarr.guibi.dev
                paths:
                  - path: /
                    pathType: ImplementationSpecific
            tls:
              - secretName: tls-guibi.dev
                hosts:
                  - radarr.guibi.dev
