apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: prometheus-repo
    namespace: default
spec:
    type: default
    url: https://prometheus-community.github.io/helm-charts
    interval: 5m
