apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: monitoring-controllers
    namespace: flux-system
spec:
    interval: 1h
    retryInterval: 2m
    dependsOn:
      - name: infra-configs
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: ./monitoring/controllers
    prune: true
    wait: true
    timeout: 10m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: monitoring-configs
    namespace: flux-system
spec:
    interval: 1h
    retryInterval: 2m
    dependsOn:
      - name: monitoring-controllers
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: ./monitoring/configs
    prune: true
    wait: true
    timeout: 5m
