apiVersion: v1
kind: PersistentVolume
metadata:
    name: transmission-download-pv
spec:
    capacity:
        storage: 200Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
        path: /mnt/Data/Media/Downloads

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: transmission-download-pvc
    namespace: apps
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
          storage: 200Gi
    volumeName: transmission-download-pv
    storageClassName: ""
