apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: transmission-download-pvc
    namespace: apps
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 200Gi
    storageClassName: openebs-zfspv
