apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: transmission
    namespace: apps
spec:
    releaseName: transmission
    chart:
        spec:
            chart: transmission
            sourceRef:
                kind: HelmRepository
                name: servarr-repo
                namespace: apps
    interval: 50m
    install:
        remediation:
            retries: 3

    values:
        deployment:
            volumes:
                downloads:
                    persistentVolumeClaim:
                        claimName: transmission-download-pvc

        ingress:
            enabled: false
