apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jackett
    namespace: apps
spec:
    releaseName: jackett
    chart:
        spec:
            chart: jackett
            sourceRef:
                kind: HelmRepository
                name: truecharts-repo
                namespace: apps
    interval: 50m
    install:
        remediation:
            retries: 3
