apiVersion: apps/v1
kind: Deployment
metadata:
    name: firefly
    namespace: firefly
spec:
    selector:
        matchLabels:
            app: firefly
    template:
        metadata:
            labels:
                app: firefly
        spec:
            containers:
                - name: firefly
                  image: fireflyiii/core:latest
                  imagePullPolicy: IfNotPresent
                  securityContext:
                      runAsUser: 33
                      runAsGroup: 33
                      runAsNonRoot: true
                      readOnlyRootFilesystem: true
                      allowPrivilegeEscalation: false
                      capabilities:
                          drop: ["ALL"]
                  livenessProbe:
                      tcpSocket:
                          port: 8080
                      initialDelaySeconds: 0
                      failureThreshold: 3
                      timeoutSeconds: 1
                      periodSeconds: 10
                  readinessProbe:
                      tcpSocket:
                          port: 8080
                      initialDelaySeconds: 0
                      failureThreshold: 3
                      timeoutSeconds: 1
                      periodSeconds: 10
                  startupProbe:
                      tcpSocket:
                          port: 8080
                      initialDelaySeconds: 0
                      failureThreshold: 30
                      timeoutSeconds: 1
                      periodSeconds: 5
                  resources:
                      limits:
                          cpu: "0.25"
                          memory: "256Mi"
                      requests:
                          cpu: "0.1"
                          memory: "128Mi"
                  ports:
                      - name: webui
                        containerPort: 8080
                        protocol: TCP
                  env:
                      - name: APP_ENV
                        value: production
                      - name: APP_DEBUG
                        value: "false"
                      - name: APP_KEY
                        valueFrom:
                            secretKeyRef:
                                name: firefly-secrets
                                key: APP_KEY
                      - name: APP_URL
                        value: https://firefly.guibi.dev
                      - name: TRUSTED_PROXIES
                        value: "**"
                      - name: TZ
                        value: America/Toronto
                      - name: DB_CONNECTION
                        value: sqlite
                      - name: CACHE_DRIVER
                        value: file
                      - name: SESSION_DRIVER
                        value: file
                      - name: AUTHENTICATION_GUARD
                        value: remote_user_guard
                      - name: AUTHENTICATION_GUARD_HEADER
                        value: HTTP_X_FORWARDED_USER
                      - name: AUTHENTICATION_GUARD_EMAIL
                        value: HTTP_X_FORWARDED_USER
                      - name: CUSTOM_LOGOUT_URL
                        value: https://firefly.guibi.dev/oauth/logout
                  volumeMounts:
                      - name: data
                        mountPath: "/var/www/html/storage"
                      - name: tmp
                        mountPath: "/tmp"

            volumes:
                - name: data
                  hostPath:
                      path: "/mnt/SSD/app-storage/firefly"
                      type: Directory
                - name: tmp
                  emptyDir: {}

            securityContext:
                seccompProfile:
                    type: RuntimeDefault
                fsGroup: 33
                fsGroupChangePolicy: "OnRootMismatch"
