apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
    name: cnpg-seaweed
    namespace: cnpg
spec:
    image: chrislusf/seaweedfs:latest
    volumeServerDiskCount: 1

    master:
        replicas: 3
        volumeSizeLimitMB: 1024

    volume:
        replicas: 3
        storageClassName: openebs-zfspv
        requests:
            storage: 20Gi

    filer:
        replicas: 3

    s3:
        replicas: 3
        iam: true

---
apiVersion: seaweed.seaweedfs.com/v1
kind: ResourceReferenceGrant
metadata:
    name: cnpg-seaweed-grant
    namespace: cnpg
spec:
    from:
        - { group: seaweed.seaweedfs.com, kind: Bucket, namespace: pocket-id }
        - { group: seaweed.seaweedfs.com, kind: S3Identity, namespace: pocket-id }
        - { group: seaweed.seaweedfs.com, kind: S3Credentials, namespace: pocket-id }
        - { group: seaweed.seaweedfs.com, kind: S3Policy, namespace: pocket-id }
        - { group: seaweed.seaweedfs.com, kind: S3PolicyBinding, namespace: pocket-id }
        - { group: seaweed.seaweedfs.com, kind: Bucket, namespace: vaultwarden }
        - { group: seaweed.seaweedfs.com, kind: S3Identity, namespace: vaultwarden }
        - { group: seaweed.seaweedfs.com, kind: S3Credentials, namespace: vaultwarden }
        - { group: seaweed.seaweedfs.com, kind: S3Policy, namespace: vaultwarden }
        - { group: seaweed.seaweedfs.com, kind: S3PolicyBinding, namespace: vaultwarden }
        - { group: seaweed.seaweedfs.com, kind: Bucket, namespace: servarr }
        - { group: seaweed.seaweedfs.com, kind: S3Identity, namespace: servarr }
        - { group: seaweed.seaweedfs.com, kind: S3Credentials, namespace: servarr }
        - { group: seaweed.seaweedfs.com, kind: S3Policy, namespace: servarr }
        - { group: seaweed.seaweedfs.com, kind: S3PolicyBinding, namespace: servarr }
    to:
        - { group: seaweed.seaweedfs.com, kind: Seaweed }
