apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: nats-repo
    namespace: opencloud
spec:
    type: default
    url: https://nats-io.github.io/k8s/helm/charts/
    interval: 5m
