apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: prowlarr
    namespace: apps
spec:
    releaseName: prowlarr
    chart:
        spec:
            chart: prowlarr
            sourceRef:
                kind: HelmRepository
                name: servarr-repo
                namespace: apps
    interval: 50m
    install:
        remediation:
            retries: 3
    values:
        application:
            urlBase: /prowlarr

        secrets:
            - name: apiKey
              value: 6ad80c0e1ce3f4c3a630e24d417708c4

        metrics:
            enabled: true

        ingress:
            enabled: true
            annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
                traefik.ingress.kubernetes.io/router.middlewares: apps-pocket-id-auth-prowlarr@kubernetescrd
                traefik.ingress.kubernetes.io/router.priority: "100"
            host: seerr.guibi.dev
            path: /prowlarr
            pathType: Prefix
            tls:
                - secretName: tls-guibi.dev
                  hosts:
                      - seerr.guibi.dev
