apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: prowlarr
    namespace: servarr
spec:
    releaseName: prowlarr
    chart:
        spec:
            chart: prowlarr
            sourceRef:
                kind: HelmRepository
                name: servarr-repo
                namespace: servarr
    interval: 50m
    install:
        remediation:
            retries: 3
    values:
        application:
            urlBase: /prowlarr

        secrets:
            - name: apiKey
              value: 6ad80c0e1ce3f4c3a630e24d417708c4

        metrics:
            enabled: true

        ingress:
            enabled: false
