apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: minio-operator
    namespace: minio
spec:
    releaseName: minio-operator
    chart:
        spec:
            chart: operator
            sourceRef:
                kind: HelmRepository
                name: minio-repo
                namespace: minio
    interval: 50m
    install:
        remediation:
            retries: 3

    values:
        operator:
