apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: tls-certificate
    namespace: servarr
spec:
    secretName: tls-guibi.dev
    issuerRef:
        name: issuer-guibi.dev
        kind: ClusterIssuer
    dnsNames:
        - radarr.guibi.dev
        - srv.guibi.dev
