apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - certificate.yaml
    - namespace.yaml
    - postgres.yaml
    - repository.yaml
    - seaweedfs.yaml
    - prowlarr
    - radarr
    - seerr
    - sonarr
    - transmission
