apiVersion: seaweed.seaweedfs.com/v1
kind: Bucket
metadata:
    name: cnpg-servarr
    namespace: servarr
spec:
    clusterRef:
        name: cnpg-seaweed
        namespace: cnpg

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
    name: cnpg-backups
    namespace: servarr
spec:
    name: cnpg-backups-servarr
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
    name: cnpg-backups-credentials
    namespace: servarr
spec:
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg
    identityRef:
        name: cnpg-backups-servarr
    secretRef:
        name: cnpg-backups-s3-credentials

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Policy
metadata:
    name: cnpg-backups-policy
    namespace: servarr
spec:
    name: cnpg-backups-policy-servarr
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg
    statements:
        - effect: Allow
          actions:
              - s3:*
          resources:
              - cnpg-servarr
              - cnpg-servarr/*

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3PolicyBinding
metadata:
    name: cnpg-backups-policy-binding
    namespace: servarr
spec:
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg
    policyRef:
        name: cnpg-backups-policy-servarr
    subjects:
        - kind: S3Identity
          name: cnpg-backups-servarr
