apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: nextcloud-cluster
    namespace: cnpg
spec:
    description: "Nextcloud cluster"
    imageName: ghcr.io/cloudnative-pg/postgresql:16.2
    instances: 1
    startDelay: 300
    stopDelay: 300
    primaryUpdateStrategy: unsupervised

    postgresql:
        parameters:
            shared_buffers: 256MB
            pg_stat_statements.max: "10000"
            pg_stat_statements.track: all
            auto_explain.log_min_duration: "10s"

    bootstrap:
        recovery:
            source: clusterBackup

        externalClusters:
          - name: clusterBackup
            barmanObjectStore:
                destinationPath: s3://nextcloud/
            endpointURL: https://minio.cnpg.svc.cluster.local
            endpointCA:
                name: cnpg-minio-tenant-ca-tls
                key: ca.crt  
            s3Credentials:
                accessKeyId:
                    name: cnpg-wal-minio-credentials
                    key: CONSOLE_ACCESS_KEY
                secretAccessKey:
                    name: cnpg-wal-minio-credentials
                    key: CONSOLE_SECRET_KEY
                wal:
                    maxParallel: 8

        # initdb:
        #     database: nextcloud
        #     owner: nextcloud
        #     secret:
        #         name: nextcloud-cluster-secret

    storage:
        storageClass: openebs-zfspv
        size: 10Gi

    backup:
        retentionPolicy: "14d"
        barmanObjectStore:
            destinationPath: s3://nextcloud/
            endpointURL: https://minio.cnpg.svc.cluster.local
            endpointCA:
                name: cnpg-minio-tenant-ca-tls
                key: ca.crt  
            s3Credentials:
                accessKeyId:
                    name: cnpg-wal-minio-credentials
                    key: CONSOLE_ACCESS_KEY
                secretAccessKey:
                    name: cnpg-wal-minio-credentials
                    key: CONSOLE_SECRET_KEY
            wal:
                compression: snappy

        # Volume snapshot backups
        volumeSnapshot:
            className: openebs-zfspv-snapshot

    monitoring:
        enablePodMonitor: true

    resources:
        requests:
            memory: "512Mi"
            cpu: "1"
        limits:
            memory: "1Gi"
            cpu: "2"

    affinity:
        enablePodAntiAffinity: true
        topologyKey: failure-domain.beta.kubernetes.io/zone

    nodeMaintenanceWindow:
        inProgress: false
        reusePVC: false

---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: nextcloud-cluster-secret
    namespace: cnpg
data:
    username: bmV4dGNsb3Vk
    password: bmV4dGNsb3Vk

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
    name: nextcloud-cluster-backup
    namespace: cnpg
spec:
    cluster:
        name: nextcloud-cluster
    method: volumeSnapshot
    schedule: "0 0 0 * * *"
    backupOwnerReference: cluster
    immediate: true
