apiVersion: v1
kind: PersistentVolume
metadata:
    name: nextcloud-data-pv
    namespace: apps
spec:
    capacity:
        storage: 2000Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
        path: /mnt/Data/NextCloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nextcloud-data-pvc
    namespace: apps
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 2000Gi
    volumeName: nextcloud-data-pv
    storageClassName: ""
