apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: issuer-selfsigned
spec:
    selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: issuer-guibi.dev
spec:
    acme:
        # Replace the email address with your own contact email
        email: laurent@guibi.dev
        # The server is replaced in /clusters/production/infrastructure.yaml
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: issuer-key-guibi.dev
        solvers:
            - dns01:
                  cloudflare:
                      apiTokenSecretRef:
                          name: cloudflare-api-token-secret
                          key: api-token

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: cert-guibi.dev
    namespace: apps
spec:
    secretName: tls-guibi.dev
    issuerRef:
        name: issuer-guibi.dev
        kind: ClusterIssuer
    dnsNames:
        - guibi.dev
        - "*.guibi.dev"
