apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuers.yaml
  - storage-class.yaml
  - snapshot-class.yaml

  - insecure-transport.yaml

  - apps-namespace.yaml
  - truecharts-repository.yaml
