apiVersion: v1
kind: PersistentVolume
metadata:
    name: seerr-config-pv
    namespace: apps
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /mnt/SSD/app-storage/seerr

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: seerr-config-pvc
    namespace: apps
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
    volumeName: seerr-config-pv
    storageClassName: ""
