apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cnpg-wal-minio
    namespace: cnpg
spec:
    releaseName: cnpg-wal-minio
    chart:
        spec:
            chart: tenant
            sourceRef:
                kind: HelmRepository
                name: minio-repo
                namespace: minio
    interval: 50m
    install:
        remediation:
            retries: 3

    values:
        tenant:
            name: cnpg
            buckets:
              - name: nextcloud
              - name: vaultwarden

            prometheusOperator: true

            pools:
              - servers: 1
                storageClassName: openebs-zfspv
