apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cloudnative-pg
    namespace: cnpg
spec:
    releaseName: cloudnative-pg
    chart:
        spec:
            chart: cloudnative-pg
            sourceRef:
                kind: HelmRepository
                name: truecharts-repo
                namespace: apps
    interval: 50m
    install:
        remediation:
            retries: 3
