apiVersion: apps/v1
kind: Deployment
metadata:
    name: home-assistant
    namespace: apps
spec:
    selector:
        matchLabels:
            app: home-assistant
    template:
        metadata:
            labels:
                app: home-assistant
        spec:
            containers:
                - name: home-assistant
                  image: ghcr.io/home-assistant/home-assistant:stable
                  imagePullPolicy: IfNotPresent
                  securityContext:
                      runAsUser: 10001
                      runAsGroup: 10001
                      runAsNonRoot: true
                      readOnlyRootFilesystem: true
                      allowPrivilegeEscalation: false
                      capabilities:
                          drop: ["ALL"]
                  livenessProbe:
                      tcpSocket:
                          port: 8123
                      initialDelaySeconds: 0
                      failureThreshold: 3
                      timeoutSeconds: 1
                      periodSeconds: 10
                  readinessProbe:
                      tcpSocket:
                          port: 8123
                      initialDelaySeconds: 0
                      failureThreshold: 3
                      timeoutSeconds: 1
                      periodSeconds: 10
                  startupProbe:
                      tcpSocket:
                          port: 8123
                      initialDelaySeconds: 0
                      failureThreshold: 30
                      timeoutSeconds: 1
                      periodSeconds: 5
                  resources:
                      limits:
                          cpu: "0.5"
                          memory: "512Mi"
                      requests:
                          cpu: "0.25"
                          memory: "256Mi"
                  ports:
                      - name: webui
                        containerPort: 8123
                        protocol: TCP
                  env:
                      - name: TZ
                        value: "America/Toronto"
                  volumeMounts:
                      - name: config
                        mountPath: "/config"
                      - name: zigbee
                        mountPath: "/dev/ttyUSB0"

            volumes:
                - name: config
                  hostPath:
                      path: "/mnt/SSD/app-storage/home-assistant"
                      type: Directory
                - name: zigbee
                  hostPath:
                      path: "/dev/ttyUSB0"
                      type: CharDevice

            securityContext:
                seccompProfile:
                    type: RuntimeDefault
                fsGroup: 10001
                fsGroupChangePolicy: "OnRootMismatch"
