apiVersion: apps/v1
kind: Deployment
metadata:
    name: home-assistant
    namespace: apps
spec:
    selector:
        matchLabels:
            app: home-assistant
    template:
        metadata:
            labels:
              app: home-assistant
        spec:
          containers:
            - name: home-assistant
              image: ghcr.io/home-assistant/home-assistant:stable
              imagePullPolicy: IfNotPresent
              securityContext:
                  privileged: true
              livenessProbe:
                  tcpSocket:
                      port: 8123
                  initialDelaySeconds: 0
                  failureThreshold: 3
                  timeoutSeconds: 1
                  periodSeconds: 10
              readinessProbe:
                  tcpSocket:
                      port: 8123
                  initialDelaySeconds: 0
                  failureThreshold: 3
                  timeoutSeconds: 1
                  periodSeconds: 10
              startupProbe:
                  tcpSocket:
                      port: 8123
                  initialDelaySeconds: 0
                  failureThreshold: 30
                  timeoutSeconds: 1
                  periodSeconds: 5
              ports:
                - name: webui
                  containerPort: 8123
                  protocol: TCP
              env:
                - name: TZ
                  value: "America/Toronto"
              volumeMounts:
                - name: config
                  mountPath: "/config"
                - name: zigbee
                  mountPath: "/dev/ttyUSB0"

          volumes:
            - name: config
              hostPath:
                  path: "/mnt/SSD/app-storage/home-assistant"
                  type: Directory
            - name: zigbee
              hostPath:
                  path: "/dev/ttyUSB0"
                  type: CharDevice
