apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: home-assistant-var
    namespace: home-assistant
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: openebs-zfspv
