apiVersion: v1
kind: PersistentVolume
metadata:
    name: jellyfin-media-pv
    namespace: apps
spec:
    capacity:
        storage: 3000Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
        path: /mnt/Data/Media

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jellyfin-media-pvc
    namespace: apps
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 3000Gi
    volumeName: jellyfin-media-pv
    storageClassName: ""

---

apiVersion: v1
kind: PersistentVolume
metadata:
    name: jellyfin-config-pv
    namespace: apps
spec:
    capacity:
        storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
        path: /mnt/SSD/app-storage/jellyfin

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jellyfin-config-pvc
    namespace: apps
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 100Gi
    volumeName: jellyfin-config-pv
    storageClassName: ""
