apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: apps
spec:
    releaseName: jellyfin
    chart:
        spec:
            chart: jellyfin
            sourceRef:
                kind: HelmRepository
                name: jellyfin-repo
                namespace: apps
    interval: 50m
    install:
        remediation:
            retries: 3
    values:
        jellyfin:
            enableDLNA: false
            env:
              - name: TZ
                value: "America/Toronto"

        persistence:
            config:
                enabled: true
                existingClaim: jellyfin-config-pvc
            media:
                enabled: true
                type: pvc
                existingClaim: jellyfin-media-pvc

        resources:
            requests:
                memory: "512Mi"
                cpu: 100m
            limits:
                memory: "2Gi"
                cpu: 2000m

        metrics:
            enabled: true
            # serviceMonitor:
            #     enabled: true
            #     namespace: monitoring
            #     interval: 30s
            #     scrapeTimeout: 10s

        service:
            type: ClusterIP

        ingress:
            enabled: true
            annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - host: jellyfin.guibi.dev
                paths:
                  - path: /
                    pathType: ImplementationSpecific
            tls:
              - secretName: tls-guibi.dev
                hosts:
                  - jellyfin.guibi.dev
