apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cnpg-wal-minio
    namespace: cnpg
spec:
    releaseName: cnpg-wal-minio
    chart:
        spec:
            chart: tenant
            sourceRef:
                kind: HelmRepository
                name: minio-repo
                namespace: minio
    interval: 50m
    install:
        remediation:
            retries: 3

    values:
        tenant:
            name: cnpg-wal-minio
            buckets:
              - name: nextcloud
              - name: vaultwarden

            configuration:
                name: cnpg-wal-minio-credentials

            configSecret:
                name: cnpg-wal-minio-credentials
                accessKey: null
                secretKey: null
                existingSecret: true

            certificate:
                requestAutoCert: false
                externalCertSecret:
                  - name: cnpg-minio-tenant-tls
                    type: cert-manager.io/v1

            prometheusOperator: true

            pools:
              - name: pool-0
                servers: 1
                storageClassName: openebs-zfspv
                size: 50Gi

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cnpg-wal-minio-credentials
    namespace: cnpg
stringData:
    MINIO_USER: cloudnative-pg
    MINIO_PASSWORD: cloudnative-pg
    config.env: |-
        export MINIO_ROOT_USER='cloudnative-pg'
        export MINIO_ROOT_PASSWORD='cloudnative-pg'
