apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: prometheus-operator
    namespace: prometheus
spec:
    releaseName: prometheus-operator
    chart:
        spec:
            chart: prometheus-operator
            sourceRef:
                kind: HelmRepository
                name: truecharts-repo
                namespace: apps
    interval: 50m
    install:
        remediation:
            retries: 3
