apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: prometheus
    namespace: monitoring
spec:
    releaseName: prometheus
    chart:
        spec:
            chart: kube-prometheus-stack
            sourceRef:
                kind: HelmRepository
                name: prometheus-repo
                namespace: prometheus
    interval: 50m
    install:
        remediation:
            retries: 3
    values:
        grafana:
            ingress:
                enabled: true
                ingressClassName: traefik
                annotations:
                    traefik.ingress.kubernetes.io/router.entrypoints: websecure
                    traefik.ingress.kubernetes.io/router.tls: "true"
                hosts:
                  - srv.guibi.dev
                tls:
                  - hosts:
                      - srv.guibi.dev
                    secretName: tls-guibi.dev
