apiVersion: seaweed.seaweedfs.com/v1
kind: Bucket
metadata:
    name: cnpg-pocket-id
    namespace: pocket-id
spec:
    clusterRef:
        name: cnpg-seaweed
        namespace: cnpg

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
    name: cnpg-backups
    namespace: pocket-id
spec:
    name: cnpg-backups-pocket-id
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
    name: cnpg-backups-credentials
    namespace: pocket-id
spec:
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg
    identityRef:
        name: cnpg-backups-pocket-id
    secretRef:
        name: cnpg-backups-s3-credentials

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Policy
metadata:
    name: cnpg-backups-policy
    namespace: pocket-id
spec:
    name: cnpg-backups-policy-pocket-id
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg
    statements:
        - effect: Allow
          actions:
              - s3:*
          resources:
              - cnpg-pocket-id
              - cnpg-pocket-id/*

---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3PolicyBinding
metadata:
    name: cnpg-backups-policy-binding
    namespace: pocket-id
spec:
    seaweedRef:
        name: cnpg-seaweed
        namespace: cnpg
    policyRef:
        name: cnpg-backups-policy-pocket-id
    subjects:
        - kind: S3Identity
          name: cnpg-backups-pocket-id
