apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: openebs
    namespace: openebs
spec:
    releaseName: openebs
    chart:
        spec:
            chart: openebs
            sourceRef:
                kind: HelmRepository
                name: openebs-repo
                namespace: openebs
    interval: 50m
    install:
        remediation:
            retries: 3

    values:
        engines:
            local.lvm.enabled: false
            replicated.mayastor.enabled: false
